<a href="https://colab.research.google.com/github/RaoUmair98/NLP/blob/main/FakeNewsClassifierUsingLSTM_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/training_data_for_nlp.csv")
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.dropna()

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [ ]:
x = df.drop('label', axis=1)

In [ ]:
x.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [ ]:
y=df['label']

In [ ]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [ ]:
x.shape

(20800, 4)

In [ ]:
y.shape

(20800,)

In [ ]:
from keras.layers import Embedding
from keras.models import Sequential
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import one_hot
from keras.layers import LSTM
from keras.layers import Dense

In [ ]:
voc_size = 10000

In [ ]:
mess = x.copy()

In [ ]:
mess['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
mess.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(mess)):
  print(i)
  review = re.sub('[^a-zA-Z]', ' ', str(mess['title'][i]))
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


Streaming output truncated to the last 5000 lines.
15800
15801
15802
15803
15804
15805
15806
15807
15808
15809
15810
15811
15812
15813
15814
15815
15816
15817
15818
15819
15820
15821
15822
15823
15824
15825
15826
15827
15828
15829
15830
15831
15832
15833
15834
15835
15836
15837
15838
15839
15840
15841
15842
15843
15844
15845
15846
15847
15848
15849
15850
15851
15852
15853
15854
15855
15856
15857
15858
15859
15860
15861
15862
15863
15864
15865
15866
15867
15868
15869
15870
15871
15872
15873
15874
15875
15876
15877
15878
15879
15880
15881
15882
15883
15884
15885
15886
15887
15888
15889
15890
15891
15892
15893
15894
15895
15896
15897
15898
15899
15900
15901
15902
15903
15904
15905
15906
15907
15908
15909
15910
15911
15912
15913
15914
15915
15916
15917
15918
15919
15920
15921
15922
15923
15924
15925
15926
15927
15928
15929
15930
15931
15932
15933
15934
15935
15936
15937
15938
15939
15940
15941
15942
15943
15944
15945
15946
15947
15948
15949
15950
15951
15952
15953
15954
15955
15956
15957
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'life life luxuri elton john favorit shark pictur stare long transcontinent flight',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'excerpt draft script donald trump q ampa black church pastor new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find hom

In [ ]:
hot = [one_hot(words, voc_size) for words in corpus]
hot

[[8542, 980, 8897, 1091, 1140, 1749, 363, 5446, 4370, 7345],
 [2611, 1674, 7327, 9192, 5913, 406, 3175],
 [1607, 524, 832, 8929],
 [7046, 2046, 6875, 1291, 3128, 3445],
 [5706, 5913, 6998, 9036, 6783, 8563, 5913, 156, 7722, 7800],
 [1662,
  9131,
  3519,
  8492,
  8257,
  8455,
  9134,
  354,
  1912,
  91,
  3399,
  4141,
  1384,
  3866,
  3175],
 [2570, 2570, 6180, 5549, 9927, 3807, 6932, 2880, 7059, 8463, 3028, 5954],
 [3813, 7625, 2709, 4888, 820, 5123, 1182, 6845, 5446, 8602, 1486],
 [6109, 755, 2159, 619, 8455, 4523, 9233, 5274, 2134, 8077, 5446, 8602, 1486],
 [441, 5524, 9949, 4670, 2624, 8843, 8455, 1037, 5446, 8602, 1486],
 [648, 4941, 6277, 9256, 1021, 9834, 6764, 729, 8455, 4676],
 [3523, 849, 4204, 8573, 3477, 7772, 2874, 2635],
 [5864, 9471, 9604, 7021, 6618, 2096, 4517, 9433, 4293, 2430, 5840],
 [1291, 3303, 1140, 9834, 8455, 2624],
 [2465, 8115, 1699, 3120, 2399, 1837, 9271, 4242, 9835],
 [3579, 2127, 8947, 6545, 2613, 2415, 4039, 5446, 8602, 1486],
 [9620, 494, 1027, 161

In [ ]:
sent_length=20
embed = pad_sequences(hot, padding='pre',  maxlen= sent_length)
print(embed)

[[   0    0    0 ... 5446 4370 7345]
 [   0    0    0 ... 5913  406 3175]
 [   0    0    0 ...  524  832 8929]
 ...
 [   0    0    0 ... 5446 8602 1486]
 [   0    0    0 ... 9741 1006  932]
 [   0    0    0 ... 3422 4913 1202]]


In [ ]:
embed[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 8542,
        980, 8897, 1091, 1140, 1749,  363, 5446, 4370, 7345], dtype=int32)

In [ ]:
dim = 40
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics =['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 40)            400000    
                                                                 
 lstm_2 (LSTM)               (None, 100)               56400     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embed), y.shape

(20800, (20800,))

In [ ]:
import numpy as np
x_final = np.array(embed)
y_final = np.array(y)

In [ ]:
x_final.shape, y_final.shape

((20800, 20), (20800,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final , test_size=0.33, random_state=0)

In [ ]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=60)

Epoch 1/10
233/233 [==============================] - 6s 15ms/step - loss: 0.3015 - accuracy: 0.8629 - val_loss: 0.1753 - val_accuracy: 0.9276
Epoch 2/10
233/233 [==============================] - 3s 13ms/step - loss: 0.1217 - accuracy: 0.9545 - val_loss: 0.1740 - val_accuracy: 0.9320
Epoch 3/10
233/233 [==============================] - 3s 13ms/step - loss: 0.0747 - accuracy: 0.9734 - val_loss: 0.2133 - val_accuracy: 0.9210
Epoch 4/10
233/233 [==============================] - 3s 12ms/step - loss: 0.0426 - accuracy: 0.9854 - val_loss: 0.2676 - val_accuracy: 0.9273
Epoch 5/10
233/233 [==============================] - 3s 13ms/step - loss: 0.0247 - accuracy: 0.9919 - val_loss: 0.3581 - val_accuracy: 0.9170
Epoch 6/10
233/233 [==============================] - 3s 13ms/step - loss: 0.0135 - accuracy: 0.9960 - val_loss: 0.3222 - val_accuracy: 0.9237
Epoch 7/10
233/233 [==============================] - 3s 13ms/step - loss: 0.0057 - accuracy: 0.9991 - val_loss: 0.4328 - val_accuracy: 0.9197

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([[4.8882509e-07],
       [9.9999917e-01],
       [9.9980253e-01],
       ...,
       [1.9409187e-03],
       [9.9581933e-01],
       [6.9902406e-08]], dtype=float32)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
confusion_matrix(y_test, y_pred)

TypeError: ignored

In [ ]:

accuracy_score(y_test, y_pred)

ValueError: ignored