<a href="https://colab.research.google.com/github/RaoUmair98/NLP/blob/main/Word_Embedding_Using_Keras_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.preprocessing.text import one_hot

In [ ]:
para = ['I am Rao Umair Ali',
        'I am a lazy person',
        'Just doing nothing at all',
        'Always complaning about meal']

In [ ]:
para

['I am Rao Umair Ali',
 'I am a lazy person',
 'Just doing nothing at all',
 'Always complaning about meal']

In [ ]:
voc_size = 10000

In [ ]:
one_hot_emd = [one_hot(kuchbhi, voc_size) for kuchbhi in para]
one_hot_emd

[[3412, 4621, 6294, 9560, 6850],
 [3412, 4621, 3239, 1923, 3043],
 [3965, 8825, 1134, 3001, 6937],
 [6450, 6611, 7142, 1598]]

In [ ]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [ ]:
import numpy as np


In [ ]:
sent_length = 10
embedd = pad_sequences(one_hot_emd, maxlen=sent_length, padding='pre')
embedd

array([[   0,    0,    0,    0,    0, 3412, 4621, 6294, 9560, 6850],
       [   0,    0,    0,    0,    0, 3412, 4621, 3239, 1923, 3043],
       [   0,    0,    0,    0,    0, 3965, 8825, 1134, 3001, 6937],
       [   0,    0,    0,    0,    0,    0, 6450, 6611, 7142, 1598]],
      dtype=int32)

In [ ]:
dim = 12

In [ ]:
model =Sequential()
model.add(Embedding(voc_size, 12, input_length=sent_length))
model.compile('adam', 'mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 10, 12)            120000    
                                                                 
Total params: 120,000
Trainable params: 120,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.predict(embedd)

array([[[-4.5334745e-02, -2.0232547e-02, -4.5648701e-03, -2.6788294e-02,
          2.9590871e-02,  2.8010514e-02, -2.8906334e-02, -3.8262915e-02,
          3.6513917e-03, -3.3645093e-02,  3.3400621e-02, -4.2528596e-02],
        [-4.5334745e-02, -2.0232547e-02, -4.5648701e-03, -2.6788294e-02,
          2.9590871e-02,  2.8010514e-02, -2.8906334e-02, -3.8262915e-02,
          3.6513917e-03, -3.3645093e-02,  3.3400621e-02, -4.2528596e-02],
        [-4.5334745e-02, -2.0232547e-02, -4.5648701e-03, -2.6788294e-02,
          2.9590871e-02,  2.8010514e-02, -2.8906334e-02, -3.8262915e-02,
          3.6513917e-03, -3.3645093e-02,  3.3400621e-02, -4.2528596e-02],
        [-4.5334745e-02, -2.0232547e-02, -4.5648701e-03, -2.6788294e-02,
          2.9590871e-02,  2.8010514e-02, -2.8906334e-02, -3.8262915e-02,
          3.6513917e-03, -3.3645093e-02,  3.3400621e-02, -4.2528596e-02],
        [-4.5334745e-02, -2.0232547e-02, -4.5648701e-03, -2.6788294e-02,
          2.9590871e-02,  2.8010514e-02, -2.890

In [ ]:
model.predict(embedd[0])

array([[-0.04533475, -0.02023255, -0.00456487, -0.02678829,  0.02959087,
         0.02801051, -0.02890633, -0.03826291,  0.00365139, -0.03364509,
         0.03340062, -0.0425286 ],
       [-0.04533475, -0.02023255, -0.00456487, -0.02678829,  0.02959087,
         0.02801051, -0.02890633, -0.03826291,  0.00365139, -0.03364509,
         0.03340062, -0.0425286 ],
       [-0.04533475, -0.02023255, -0.00456487, -0.02678829,  0.02959087,
         0.02801051, -0.02890633, -0.03826291,  0.00365139, -0.03364509,
         0.03340062, -0.0425286 ],
       [-0.04533475, -0.02023255, -0.00456487, -0.02678829,  0.02959087,
         0.02801051, -0.02890633, -0.03826291,  0.00365139, -0.03364509,
         0.03340062, -0.0425286 ],
       [-0.04533475, -0.02023255, -0.00456487, -0.02678829,  0.02959087,
         0.02801051, -0.02890633, -0.03826291,  0.00365139, -0.03364509,
         0.03340062, -0.0425286 ],
       [-0.01552325,  0.04693724, -0.00320696,  0.01041777,  0.04487116,
         0.00104698, -